USE COLLEGE_DB;

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES;

SELECT FIRST_NAME AS 'First Name'
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'IT'
ORDER BY DEPARTMENT_ID DESC;

SELECT *
FROM EMPLOYEES
LIMIT 1;

SELECT *
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID DESC
LIMIT 1;

SELECT DEPARTMENT_NAME
FROM DEPARTMENTS;

SELECT DISTINCT DEPARTMENT_NAME
FROM DEPARTMENTS;

SELECT EMPLOYEES.SALARY
FROM EMPLOYEES;

SELECT EMPLOYEES.SALARY * 2 AS 'SALARY AFTER x2'
FROM EMPLOYEES;

SELECT CONCAT(EMPLOYEES.FIRST_NAME, ' ', EMPLOYEES.LAST_NAME) AS "Full Name", YEAR(HIRE_DATE) AS "HIRE DATE YR"
FROM EMPLOYEES;

SELECT ROUND(EMPLOYEES.SALARY, 0)
FROM EMPLOYEES;

SELECT FIRST_NAME, ROUND(EMPLOYEES.SALARY, 0)
FROM EMPLOYEES
WHERE SALARY > 10000;

SELECT ROUND(AVG(SALARY))
FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT EMPLOYEES.SALARY
FROM EMPLOYEES;

SELECT AVG(EMPLOYEES.SALARY)
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 2;

UPDATE EMPLOYEES
SET SALARY = 15000
WHERE EMPLOYEE_ID = 3;

-- SUB QUERY
SELECT *
FROM EMPLOYEES
WHERE SALARY >= (SELECT AVG(EMPLOYEES.SALARY) FROM EMPLOYEES);

SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME
FROM EMPLOYEES
WHERE SALARY = 15000;

SELECT DEPARTMENT_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'IT'
UNION
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'HR';


SELECT COUNT(*), DEPARTMENT_NAME
FROM DEPARTMENTS
GROUP BY DEPARTMENT_NAME;


SELECT NOW() AS TIME;

SELECT LENGTH('SAM');

/*SELECT (2 < 5);

SELECT (2 > 5);*/

SELECT FIRST_NAME, EMAIL
FROM EMPLOYEES;