
CREATE DATABASE COMPANY;
USE COMPANY;

CREATE TABLE EMPLOYEES
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME  VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY     DECIMAL(10, 2),
    HIRE_DATE  DATE
);

INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, DEPARTMENT, SALARY, HIRE_DATE)
VALUES ('JOHN', 'DOE', 'HR', 60000.00, '2022-05-10'),
       ('JANE', 'SMITH', 'IT', 75000.00, '2021-08-15'),
       ('ALICE', 'JOHNSON', 'FINANCE', 82000.00, '2019-03-20'),
       ('BOB', 'WILLIAMS', 'IT', 72000.00, '2020-11-25'),
       ('CHARLIE', 'BROWN', 'MARKETING', 65000.00, '2023-01-05');

SELECT *
FROM EMPLOYEES;

SELECT FIRST_NAME AS 'FIRST NAME', LAST_NAME, DEPARTMENT
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT = 'IT'
ORDER BY SALARY DESC
LIMIT 1;

SELECT *
FROM EMPLOYEES
LIMIT 2;

SELECT DISTINCT DEPARTMENT
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY * 1.1 AS 'SALARY AFTER RAISE'
FROM EMPLOYEES;

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS 'FULL NAME',
       YEAR(HIRE_DATE),
       ROUND(SALARY, 1)
FROM EMPLOYEES
WHERE SALARY > 70000;

SELECT AVG(SALARY)
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT = 'IT'
UNION
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT = 'HR';

SELECT COUNT(*), DEPARTMENT
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT NOW() AS 'TIME';

SELECT 5 * 2;

SELECT LENGTH('HELLO');

SELECT 5 < 3;
