CREATE DATABASE IF NOT EXISTS BOOKSTORE;

USE BOOKSTORE;

CREATE TABLE BOOKS
(
    BOOK_ID          INT PRIMARY KEY,
    TITLE            VARCHAR(100),
    AUTHOR           VARCHAR(50),
    PRICE            DECIMAL(10, 2),
    PUBLICATION_DATE DATE,
    CATEGORY         VARCHAR(30),
    INT_STOCK        INT
);

INSERT INTO BOOKS (BOOK_ID, TITLE, AUTHOR, PRICE, PUBLICATION_DATE, CATEGORY, INT_STOCK)
VALUES (1, 'JAVA PROGRAMMING BASICS', 'JAMES GOSLING', 450.50, '2015-06-10', 'PROGRAMMING', 25),
       (2, 'SPRING BOOT IN ACTION', 'CRAIG WALLS', 550.00, '2018-03-15', 'BACKEND', 18),
       (3, 'DATA STRUCTURES AND ALGORITHMS', 'ROBERT SEDGEWICK', 600.75, '2012-09-20', 'COMPUTER SCIENCE', 30),
       (4, 'DATABASE SYSTEM CONCEPTS', 'ABRAHAM SILBERSCHATZ', 700.00, '2010-01-05', 'DATABASE', 12),
       (5, 'OPERATING SYSTEM CONCEPTS', 'PETER GALVIN', 650.40, '2014-11-25', 'SYSTEMS', 20);



ALTER TABLE BOOKS
    ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE BOOKS
    ADD COLUMN UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

SELECT *
FROM BOOKS;

SELECT *
FROM BOOKS
WHERE CATEGORY = 'COMPUTER SCIENCE';

SELECT TITLE, PRICE
FROM BOOKS
WHERE PRICE > 10;

SELECT BOOKS.BOOK_ID, BOOKS.TITLE
FROM BOOKS
WHERE PRICE = 450.50;

SELECT BOOKS.TITLE, BOOKS.PUBLICATION_DATE
FROM BOOKS
WHERE PUBLICATION_DATE > '2010-02-01'

SELECT BOOKS.TITLE, BOOKS.CATEGORY
FROM BOOKS
WHERE CATEGORY = 'BACKEND'
  AND PRICE > 400;

SELECT BOOKS.TITLE, BOOKS.CATEGORY, PRICE
FROM BOOKS
WHERE CATEGORY = 'BACKEND'
   OR PRICE = 400;

SELECT *
FROM BOOKS
WHERE (CATEGORY = 'DATABASE' OR CATEGORY = 'BACKEND')
  AND PRICE > 500;

SELECT *
FROM BOOKS
WHERE NOT CATEGORY = 'DATABASE';

SELECT *
FROM BOOKS
WHERE CATEGORY != 'DATABASE';

INSERT INTO BOOKS (BOOK_ID, TITLE, AUTHOR, PUBLICATION_DATE, CATEGORY, INT_STOCK)
VALUES (6, 'JAVA PROGRAMMING BASICS', 'JAMES GOSLING', '2015-06-10', 'PROGRAMMING', 25);


SELECT *
FROM BOOKS
WHERE PRICE IS NULL;


SELECT *
FROM BOOKS
WHERE NOT PRICE IS NULL;

-- WHERE NOT PRICE = NULL; WRONG IT GIVES UNKNOWN OR WHERE RUN TRUE STATEMENT

SELECT *
FROM BOOKS
WHERE PRICE IS NOT NULL;

-- PATTERN MATCHING
SELECT *
FROM BOOKS
WHERE TITLE LIKE '%sys%';
-- CASE INSENSITIVE
SELECT *
FROM BOOKS
WHERE TITLE LIKE '%SYSTEM%';

SELECT *
FROM BOOKS
WHERE TITLE LIKE 'DATA%';

-- CASE SENSITIVE => USE BINARY
SELECT *
FROM BOOKS
WHERE TITLE LIKE BINARY '%DAtA%';

UPDATE BOOKS
SET AUTHOR = 'GAMES'
WHERE BOOK_ID = '1';

SELECT *
FROM BOOKS
WHERE AUTHOR LIKE BINARY '_AMES%';

SELECT *
FROM BOOKS
WHERE PRICE BETWEEN 200 AND 700;

SELECT *
FROM BOOKS
WHERE CATEGORY IN ('PROGRAMMING', 'BACKEND');

SELECT *
FROM BOOKS
WHERE PRICE BETWEEN 200 AND 700
  AND PUBLICATION_DATE >= '2000-02-01';

SELECT *
FROM BOOKS
WHERE PRICE > (SELECT AVG(PRICE) FROM BOOKS);

SELECT *
FROM BOOKS
WHERE CATEGORY IN (SELECT CATEGORY FROM BOOKS WHERE INT_STOCK > 21);

-- Find all books published in 2023 that cost less than the average book price

-- List all technology books with "data" in the title that have more than 50 copies in stock

-- Find books that are either in the Technology category with price > $30 or in the Mystery category with price < $20

-- List all books where the author's name contains either 'son' or 'th' and were published after March 2023