-- CREATE DATABASE
CREATE DATABASE COLLEGE_DB;

-- USE DATABASE [ USE CMD USED TO SELECT BECAUSE MANY DB ]
USE COLLEGE_DB;

-- DROP DATABASE
DROP DATABASE COLLEGE_DB;

-- SHOW ALL DATABASE
SHOW DATABASES;

-- SHOW CURRENT DATABASE ( FUNCTION )
SELECT DATABASE();

-- CREATE TABLE
CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID       INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME        VARCHAR(50) NOT NULL,
    LAST_NAME         VARCHAR(50) NOT NULL,
    HIRE_DATE         DATE                                       DEFAULT (CURRENT_DATE()),
    EMAIL             VARCHAR(100) UNIQUE,
    PHONE_NO          VARCHAR(100) UNIQUE,
    SALARY            DECIMAL(10, 2) CHECK ( SALARY > 0.0 ),
    EMPLOYMENT_STATUS ENUM ('ACTIVE' , 'ON LEAVE', 'TERMINATED') DEFAULT ('ACTIVE'),
    CREATED_AT        TIMESTAMP                                  DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        TIMESTAMP                                  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO EMPLOYEES(FIRST_NAME, LAST_NAME, EMAIL, PHONE_NO, SALARY)
    VALUE ('Shivam', 'Jha', 'sm@gmail.com', 7703971734, 10000);

INSERT INTO EMPLOYEES(FIRST_NAME, LAST_NAME, EMAIL, PHONE_NO, SALARY, EMPLOYMENT_STATUS)
    VALUE ('Summit', 'Jha', 'st@gmail.com', 6200129832, 10000, 'ON LEAVE');

SELECT *
FROM EMPLOYEES;

UPDATE EMPLOYEES
SET SALARY = 15000
WHERE EMPLOYEE_ID = 1;

UPDATE EMPLOYEES
SET EMAIL = 'shivamkumarsaitm@gmail.com'
WHERE EMPLOYEE_ID = 1;

UPDATE EMPLOYEES
SET EMAIL = 'sumitjhawiki@gmail.com'
WHERE EMPLOYEE_ID = 3;

SELECT VERSION();

DROP TABLE EMPLOYEES;


CREATE TABLE DEPARTMENTS
(
    DEPARTMENT_ID   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(100) NOT NULL,
    LOCATION        VARCHAR(100) NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    -- , FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);

-- OPTIONALS IGNORE
ALTER TABLE DEPARTMENTS
    MODIFY DEPARTMENT_ID INT NOT NULL AUTO_INCREMENT;

DROP TABLE DEPARTMENTS;

SELECT *
FROM DEPARTMENTS;

-- ALTER IS USED TO CHANGE THE STRUCTURE OF AN EXISTING TABLE
-- DATA REMAINS SAFE, ONLY STRUCTURE CHANGES
-- GENERAL SYNTAX

-- ALTER TABLE TABLE_NAME
--  ACTION;

ALTER TABLE EMPLOYEES
    ADD COLUMN DESCRIPTION TEXT;


-- UPDATE TABLE
UPDATE EMPLOYEES
SET DESCRIPTION = 'HELLO SHIVAM'
WHERE EMPLOYEE_ID = 1;


UPDATE EMPLOYEES
SET DESCRIPTION = 'HELLO SUMMIT'
WHERE EMPLOYEE_ID = 3;

/*
-- WRONG CODE
ALTER TABLE EMPLOYEES
    ADD COLUMN EMERGENCY_CONTACT VARCHAR(15)
        NOT NULL
        CHECK (EMERGENCY_CONTACT REGEXP '^[0-9]{10}$');
-- [2026-01-15 13:03:39] [HY000][3819] Check constraint 'EMPLOYEES_chk_2' is violated.
*/

-- STEP 1
ALTER TABLE EMPLOYEES
    ADD COLUMN EMERGENCY_CONTACT VARCHAR(15);

-- STEP 2
UPDATE EMPLOYEES
SET EMPLOYEES.EMERGENCY_CONTACT = '7703971734'
WHERE EMPLOYEE_ID = 1;


UPDATE EMPLOYEES
SET EMPLOYEES.EMERGENCY_CONTACT = '6200129832'
WHERE EMPLOYEE_ID = 3;

-- STEP 3 ADD CONSTRAINTS
ALTER TABLE EMPLOYEES
    MODIFY EMERGENCY_CONTACT VARCHAR(100) NOT NULL;

ALTER TABLE EMPLOYEES
    ADD CHECK (EMERGENCY_CONTACT REGEXP '^[0-9]{10}$');
/*
-- ===== ALL ALTER COMMANDS WITH COMMENTS (SQL) START =====
-- ADD A NEW COLUMN TO TABLE
ALTER TABLE EMPLOYEES
    ADD COLUMN DEPARTMENT VARCHAR(50);

-- MODIFY EXISTING COLUMN DATATYPE / SIZE
ALTER TABLE EMPLOYEES
    MODIFY SALARY DECIMAL(12,2);

-- RENAME A COLUMN
ALTER TABLE EMPLOYEES
    RENAME COLUMN PHONE_NO TO MOBILE_NO;

-- DROP (DELETE) A COLUMN
ALTER TABLE EMPLOYEES
    DROP COLUMN MOBILE_NO;

-- ADD A PRIMARY KEY
ALTER TABLE EMPLOYEES
    ADD PRIMARY KEY (EMPLOYEE_ID);

-- ADD A UNIQUE CONSTRAINT
ALTER TABLE EMPLOYEES
    ADD CONSTRAINT UQ_EMAIL UNIQUE (EMAIL);

-- ADD A CHECK CONSTRAINT
ALTER TABLE EMPLOYEES
    ADD CONSTRAINT CHK_SALARY CHECK (SALARY > 0);

-- DROP A CONSTRAINT
ALTER TABLE EMPLOYEES
    DROP CONSTRAINT CHK_SALARY;

-- ADD A FOREIGN KEY
ALTER TABLE EMPLOYEES
    ADD CONSTRAINT FK_DEPT
        FOREIGN KEY (DEPARTMENT_ID)
            REFERENCES DEPARTMENTS(DEPARTMENT_ID);

-- DROP A FOREIGN KEY
ALTER TABLE EMPLOYEES
    DROP FOREIGN KEY FK_DEPT;

-- CHANGE COLUMN NAME + DATATYPE (MYSQL)
ALTER TABLE EMPLOYEES
    CHANGE FIRST_NAME FAME VARCHAR(50);

-- RENAME TABLE
ALTER TABLE EMPLOYEES
    RENAME TO STAFF;

-- ADD DEFAULT VALUE TO COLUMN
ALTER TABLE EMPLOYEES
    ALTER SALARY SET DEFAULT 30000;

-- REMOVE DEFAULT VALUE
ALTER TABLE EMPLOYEES
    ALTER SALARY DROP DEFAULT;

-- ===== ALL ALTER COMMANDS WITH COMMENTS (SQL) END =====
 */


ALTER TABLE EMPLOYEES
    ADD COLUMN DEPARTMENT_ID INT;

UPDATE EMPLOYEES
SET EMPLOYEES.DEPARTMENT_ID = 1
WHERE EMPLOYEE_ID = 1;

UPDATE EMPLOYEES
SET EMPLOYEES.DEPARTMENT_ID = 2
WHERE EMPLOYEE_ID = 3;


ALTER TABLE EMPLOYEES
    MODIFY COLUMN DEPARTMENT_ID INT NOT NULL;

ALTER TABLE EMPLOYEES
    ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID);

INSERT INTO DEPARTMENTS(DEPARTMENT_NAME, LOCATION)
VALUES ('IT', 'GURGAON'),
       ('HR', 'NOIDA');

SELECT *
FROM DEPARTMENTS;


INSERT INTO EMPLOYEES(FIRST_NAME, LAST_NAME, EMAIL, PHONE_NO, SALARY,EMERGENCY_CONTACT,DEPARTMENT_ID)
VALUES ('Abhinesh','Jha', 'jhaabhinesh977@gmail.com','9334305214','15000','9334305214',2);

DROP TABLE EMPLOYEES,DEPARTMENTS;

DROP TABLE IF EXISTS SAM;